name: optional-check
on: [pull_request]
jobs:
  optional:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "this one we will leave non-required"
          # toggle this between 'exit 0' and 'exit 1' per PR to make it pass/fail
          exit 1

